### ISSUE TITLE
🚀[FEA]: Overwriting NetCDF4 output files

### ISSUE THREAD

**Issue by jleinonen** [NVIDIA/earth2studio#105]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

Trying to write to a NetCDF4 file that already exists currently produces the following error:
```python
AssertionError: Warning! <variable> is already in the NetCDF Store.
```
This is not particularly clear as to the nature of what went wrong. I also think most people would expect that the default behavior is to overwrite the file if it already exists, as most utilities do. I'd suggest two improvements:
1. Make the error message clearer as to why it occurred (i.e. the file already existed)
2. Add an option to overwrite any existing file (maybe even make it the default behavior)

Item 2 should be achievable by using write mode `w` instead of `r+` in:
https://github.com/NVIDIA/earth2studio/blob/c90c04d0d54de465a4891936f3c9f46918f80312/earth2studio/io/netcdf4.py#L52-L58

**Comment by NickGeneva** [comment]
Re-opening to add more informative error when write fails. (suggest a backend)
