### ISSUE TITLE
🐛[BUG]: ablation_sampler removal from modulus

### ISSUE THREAD

**Issue by dallasfoster** [NVIDIA/earth2studio#114]
### Version

main

### On which installation method(s) does this occur?

Source

### Describe the issue

Because of a new PR to modulus: https://github.com/NVIDIA/modulus/pull/644

`ablation_sampler` has been removed from `modulus.utils.generative` with `deterministic_sampler`.

**Comment by dallasfoster** [comment]
Recommended solution:

```python
try: 
    from modulus.utils.generative import ablation_sampler
except ImportError:
   from modulus.utils.generative import deterministic_sampler as ablation_sampler
```

**Comment by NickGeneva** [comment]
Fixed in RC Branch: https://github.com/NVIDIA/earth2studio/pull/136
