### ISSUE TITLE
🚀[FEA]: Use GEFS members as initial condition data source

### ISSUE THREAD

**Issue by djzurawski** [NVIDIA/earth2studio#143]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

I would like to be able to select a GEFS member to use for initial conditions for a prognostic model. A few weeks ago I attempted to repurpose the GEFS_FX forecast source but failed.

**Comment by NickGeneva** [comment]
Hi @djzurawski 

How did it fail can you provide some details?
Did selecting the member with the [product](https://github.com/NVIDIA/earth2studio/blob/main/earth2studio/data/gefs.py#L393) string not work as intended?

**Comment by djzurawski** [comment]
This solution should have been obvious to me the first time I dont know why it wasnt. The `DataArray` returned from `data.GEFS_FX` calls contain `lead_time` as a coordinate which the initialization datasources like `data.GFS` do not have which was the source of my errors. I got it working by creating a child class of GEFS_FX which selects the 0 `lead_time` (or any `lead_time` you want for time-lagging).

```python
class GEFS_INIT(GEFS_FX):

    def __call__(
        self,
        time: datetime | list[datetime] | TimeArray,
        variable: str | list[str] | VariableArray,
    ) -> xr.DataArray:

        da = super().__call__(time=time, lead_time=timedelta(0), variable=variable)
        return da.isel(lead_time=0)
```

Then you can follow the Readme quickstart example
```python
model = DLWP.load_model(DLWP.load_default_package())
ds = GEFS_INIT(product="gep10")
io = NetCDF4Backend("output.nc")

run(["2024-01-01"], 10, model, ds, io)
```
