### ISSUE TITLE
🚀[FEA]: Will Earth2Studio support training of AI weather models？

### ISSUE THREAD

**Issue by LevineHuang** [NVIDIA/earth2studio#145]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

 Will Earth2Studio support training of AI weather models？

**Comment by NickGeneva** [comment]
Hi @LevineHuang 

At the moment Earth2Studio is a inference focused package. Training of weather AI models is something we leave to other repos, whether modulus, makani or the research repo's that are tied to a particular model. I do know some of the utils inside Earth2Studio can be potentially useful for training (such as fetching data). 

So some components could be improved based on peoples needs. Did you have something particular in mind?
