### ISSUE TITLE
🐛[BUG]: fuxi:'Could not find variable tp06 in index file'

### ISSUE THREAD

**Issue by wlu1998** [NVIDIA/earth2studio#153]
### Version

0.3.0

### Describe the issue

GFSLexicon don't have tp06, but tp06 is in fuxi model VARIABLES. The variable related to precipitation in GFSLexicon is 'tcwv': 'PWAT::entire atmosphere (considered as a single layer)'，but it should be different from the six hour cumulative precipitation variable.

**Comment by NickGeneva** [comment]
Hi @wlu1998 

NOAA's data sources don't offer a tp06 like variable. The best offered is tp accumulated over the past 3 hours:

`597	surface	APCP	0-3 hour acc	Total Precipitation [kg/m^2]`

which we can add, however this won't work with FuXi exactly but would be close enough potentially. tp06 is best found in the weather bench 2 dataset. I have also seen some scripts with GFS that just feed in a zero array for tp06, but thats not ideal.

**Comment by NickGeneva** [comment]
Let me know if there is a specific variable you have in mind from GFS.

**Comment by wlu1998** [comment]
> Hi [@wlu1998](https://github.com/wlu1998)
> 
> NOAA's data sources don't offer a tp06 like variable. The best offered is tp accumulated over the past 3 hours:
> 
> `597 surface APCP 0-3 hour acc Total Precipitation [kg/m^2]`
> 
> which we can add, however this won't work with FuXi exactly but would be close enough potentially. tp06 is best found in the weather bench 2 dataset. I have also seen some scripts with GFS that just feed in a zero array for tp06, but thats not ideal.

ok，thanks！
