### ISSUE TITLE
SFNO parameter for IFS initial condition

### ISSUE THREAD

**Issue by david5010** [NVIDIA/earth2studio#156]
Looking into the SFNO model, it seems that it uses "Z" at different pressure levels. However, from what I remember, IFS does not provide "Z" but only "GH" (at least from opendata). I'm wondering where and how the GH is transformed to "Z" in this whole process. I tried digging through the files but couldn't find much

**Comment by NickGeneva** [comment]
Conversions between things like geo-potential height and geo-potential occur in the lexicons where the variables are defined:
