### ISSUE TITLE
🐛[BUG]:Error when running Diagnostic Module: odule 'earth2studio.run' has no attribute 'diagnostic'

### ISSUE THREAD

**Issue by awesomemfg** [NVIDIA/earth2studio#94]
### Version

0.1.0

### On which installation method(s) does this occur?

Pip

### Describe the issue

![image](https://github.com/user-attachments/assets/59614fe6-6726-4928-bf2c-84f9f590b79e)

Steps leading to the error:

1. Using the Modulus Docker
2. Installing Makani and Earth2Studio v0.1.0
3. Downloading the example notebook file in https://nvidia.github.io/earth2studio/examples/02_diagnostic_workflow.html
4. Trying to run the run.diagnostic

```
import earth2studio.run as run

nsteps = 8
io = run.diagnostic(
    ["2021-06-01"], nsteps, prognostic_model, diagnostic_model, data, io
)

print(io.root.tree())
```

Notes

1. The Deterministic/Prognostic model works.
2. No Diagnostic function in .local/lib/python3.10/site-packages/earth2studio/run.py

Do I have to install anything else to get the Diagnostic model running? Thank you

**Comment by NickGeneva** [comment]
Hi @awesomemfg 

The diagnostic workflow was added in [0.2.0](https://github.com/NVIDIA/earth2studio/blob/main/CHANGELOG.md#added-1) which is being prepared for release. For now you will need to [install from source](https://nvidia.github.io/earth2studio/userguide/about/install.html#install-from-source). Give that a go and let me know if you're still having trouble.

Make sure the docs version you are referencing matches the install version of the package.

**Comment by awesomemfg** [comment]
Dear Nick,

Thanks for the clarification! I'll try installing from the source.

**Comment by awesomemfg** [comment]
Dear Nick, everything went smoothly when I installed from the source. Thank you!
